### ISSUE TITLE
Prowlarr

### ISSUE THREAD

**Issue by JourneyOver** [JourneyOver/chocolatey-packages#57]
https://github.com/Prowlarr/Prowlarr

**Comment by Yankees4life** [comment]
Any updates on this?

**Comment by JourneyOver** [comment]
not really no, I've just been busy with so many other things and dealing with shit outside of the online world that I kind of forgot all about this and other packages that I have wanted to do as well, and just don't really have time at the moment.. I might look into adding this sometime this week.

**Comment by JourneyOver** [comment]
This is now up --- https://community.chocolatey.org/packages/prowlarr
