### ISSUE TITLE
Need help about gitcr***en

### ISSUE THREAD

**Issue by LOVEChen** [JourneyOver/chocolatey-packages#58]
The original link 8.2.0 you replied was removed, 
can you transfer one zip to mega/wetransfer or other online disk?
Thank you very much!!

**Comment by JourneyOver** [comment]
What are you even talking about?? if you're talking about a crack for gitkraken then I am not providing links to that as it has been DMCA'd, and also this is not the place to ask for such things!

**Comment by LOVEChen** [comment]
ok thanks anyway
